### ISSUE TITLE
Create CI script for AKS

### ISSUE THREAD

**Issue by dgozalo** [jenkins-x/terraform-azurerm-jx#6] opened 2020-03-04 13:41 UTC
# Summary
We want to test the correctness and validity of the Terraform modules per provider on each PR in this repository.

There will need to be a script for AKS that will run its Terraform module, create a cluster and any necessary resources, and validate that everything was created correctly based on the parameters that were passed and the state that was created.

# Acceptance Criteria
A script that will run Terraform for the current AKS module and verify that the generated state is correct.

**Comment by hferentschik** [comment] 2020-04-13 17:20
Closing - duplicate of #2

**Closed as completed by hferentschik** 2020-04-13 17:20 UTC
